export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_LECTURER = "GET_LECTURER";
export const LECTURER_LOADING = "LECTURER_LOADING";
export const LECTURER_NOT_FOUND = "LECTURER_NOT_FOUND";
export const CLEAR_CURRENT_LECTURER = "CLEAR_CURRENT_LECTURER";
